"""newtab;e

Revision ID: dc00357dbd26
Revises: 
Create Date: 2024-10-08 23:01:17.914979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc00357dbd26'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('make', sa.String(length=250), nullable=True),
    sa.Column('model', sa.String(length=250), nullable=True),
    sa.Column('trim', sa.String(length=500), nullable=True),
    sa.Column('dealer_name', sa.String(length=500), nullable=True),
    sa.Column('dealer_street', sa.String(length=500), nullable=True),
    sa.Column('dealer_city', sa.String(length=500), nullable=True),
    sa.Column('dealer_state', sa.String(length=500), nullable=True),
    sa.Column('dealer_zip', sa.String(length=500), nullable=True),
    sa.Column('listing_price', sa.Integer(), nullable=True),
    sa.Column('listing_mileage', sa.Integer(), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('certified', sa.Boolean(), nullable=True),
    sa.Column('style', sa.String(length=500), nullable=True),
    sa.Column('driven_wheels', sa.String(length=500), nullable=True),
    sa.Column('engine', sa.String(length=500), nullable=True),
    sa.Column('vin', sa.String(length=500), nullable=True),
    sa.Column('fuel_type', sa.String(length=500), nullable=True),
    sa.Column('exterior_color', sa.String(length=500), nullable=True),
    sa.Column('interior_color', sa.String(length=500), nullable=True),
    sa.Column('seller_website', sa.String(length=500), nullable=True),
    sa.Column('first_seen_date', sa.String(length=500), nullable=True),
    sa.Column('last_seen_date', sa.String(length=500), nullable=True),
    sa.Column('dealer_vdp_last_seen_date', sa.String(length=500), nullable=True),
    sa.Column('listing_status', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vin')
    )
    op.create_index('ix_vehicle_make_model', 'vehicles', ['make', 'model'], unique=False)
    op.create_index('ix_vehicle_price_mileage', 'vehicles', ['listing_price', 'listing_mileage'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vehicle_price_mileage', table_name='vehicles')
    op.drop_index('ix_vehicle_make_model', table_name='vehicles')
    op.drop_table('vehicles')
    # ### end Alembic commands ###
